#!/usr/bin/env python3
"""Generates ASSETS.md from the layer declarations.

The brief an illustrator works from and the art the plugin loads come from the same
source, so the document cannot drift out of date: regenerate it whenever vbd_layers.py
changes.

    python tools/make_assets_doc.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools", "blender"))

import vbd_layers  # noqa: E402

CHANNEL_DOC = {
    "breathe": "Slow idle breathing, about 0.28 Hz. Vertical scale, roughly 1%.",
    "sway_slow": "Low-stiffness spring rotation about the pivot, driven by low-end energy.",
    "sway_fast": "High-stiffness spring rotation. Secondary motion on top of sway_slow.",
    "low_energy": "Extra rotation proportional to bass energy in the output.",
    "head_bob": "Vertical offset locked to host tempo, taken from the playhead.",
    "blink": "Vertical squash to zero and back. Fires at random intervals of 1.6-5.8 s.",
    "mouth": "Selects one of the mouth variants. Only one is drawn at a time.",
    "eye_track": "Small translation following the mouse pointer.",
    "spectral_glow": "Colour wash whose hue follows the spectral centroid of the output.",
    "react": "One-shot emphasis when the character is clicked or the randomiser fires.",
    "spline_head": "Rides the head position at the front of the dragon's spline.",
    "look_at": "Rotation towards the mouse pointer.",
    "wing_flap": "Vertical scale oscillating at half the host tempo.",
    "band_energy": "Brightness driven by the matching fractal band's live energy.",
    "tail_drag": "Rotation driven by the user dragging the tail along its arc.",
    "roar": "One-shot scale-up when the dragon is clicked.",
    "fire": "Alpha driven by input transients and the roar state.",
    "ghost_trail": "Redrawn at earlier spline phases when a delay is on.",
}


def describe_channel(name):
    if name in CHANNEL_DOC:
        return CHANNEL_DOC[name]

    if name.startswith("spline_"):
        return "Rides position %s along the dragon's spline path." % name.split("_", 1)[1]

    return "(no description yet)"


def table(layers):
    lines = [
        "| Layer | z | Pivot (x, y) | Animation channels |",
        "|---|---|---|---|",
    ]

    for layer in sorted(layers, key=lambda item: item["z"]):
        pivot = layer.get("pivot", (0.5, 0.5))
        channels = ", ".join("`%s`" % c for c in layer.get("channels", [])) or "-"
        lines.append("| `%s` | %d | %.3f, %.3f | %s |"
                     % (layer["name"], layer["z"], pivot[0], pivot[1], channels))

    return "\n".join(lines)


def main():
    used = set()

    for _, _, layer in vbd_layers.all_layers():
        used.update(layer.get("channels", []))

    out = []
    w = out.append

    w("# VIIBEDEALER - Art Brief")
    w("")
    w("*Generated by `tools/make_assets_doc.py` from `tools/blender/vbd_layers.py`.*")
    w("*Regenerate rather than editing by hand, so the brief and the code cannot drift apart.*")
    w("")
    w("This is exactly what to deliver to replace the placeholder art. Dropping final files")
    w("in requires **no code changes**: the rig reads layer names, pivots, z-order and")
    w("animation channels from `assets/manifest.json`.")
    w("")
    w("---")
    w("")
    w("## What to deliver")
    w("")
    w("One transparent PNG per layer listed below, plus a regenerated `manifest.json`.")
    w("")
    w("| Property | Requirement |")
    w("|---|---|")
    w("| Format | PNG, RGBA, 8 bits per channel, straight (non-premultiplied) alpha |")
    w("| Colour space | sRGB, no embedded ICC profile |")
    w("| Resolution | Deliver at **@2x**; the 1x set is derived by downscale |")
    w("| Character canvas | %d x %d at 1x (%d x %d at @2x) |"
      % (vbd_layers.CHARACTER_CANVAS[0], vbd_layers.CHARACTER_CANVAS[1],
         vbd_layers.CHARACTER_CANVAS[0] * 2, vbd_layers.CHARACTER_CANVAS[1] * 2))
    w("| Dragon canvas | %d x %d at 1x |" % vbd_layers.DRAGON_CANVAS)
    w("| Scene canvas | %d x %d at 1x |" % vbd_layers.SCENE_CANVAS)
    w("| Alignment | **Every layer full-canvas, same origin.** Do not crop or trim - the pipeline crops and records the offset |")
    w("| Naming | `<group>_<layer>.png`, e.g. `character_front_hair.png`, `dragon_wing_l.png` |")
    w("")
    w("## Pivot convention")
    w("")
    w("Pivots are **normalised canvas coordinates**: `0,0` is the top-left, `1,1` the")
    w("bottom-right, x right and y **down**. They are semantic rather than geometric - hair")
    w("swings about the scalp, not about the centre of its bounding box. If your artwork")
    w("moves a feature significantly, update the pivot in `vbd_layers.py` to match.")
    w("")
    w("## Style")
    w("")
    w("Original characters only. Nothing may reproduce an existing anime character, studio")
    w("design, or logo.")
    w("")
    w("- Clean line art with cel shading: two or three flat tones per surface, soft gradient")
    w("  only in the falloff, no painterly rendering.")
    w("- A glowing rim light in the neon palette, reading as light rather than as an outline.")
    w("- The character is an **adult** original female character. The dragon is serpentine,")
    w("  eastern-styled, and coils around the fractal visualiser.")
    w("")
    w("Palette, matching `src/gui/Theme.h`:")
    w("")
    w("| Role | RGB | Hex |")
    w("|---|---|---|")

    for label, rgb in (("Neon (primary accent)", vbd_layers.NEON),
                       ("Violet", vbd_layers.VIOLET),
                       ("Magenta", vbd_layers.MAGENTA),
                       ("Amber", vbd_layers.AMBER),
                       ("Lime", vbd_layers.LIME),
                       ("Deep (near-black)", vbd_layers.DEEP)):
        hexcode = "#%02X%02X%02X" % tuple(int(round(c * 255)) for c in rgb)
        w("| %s | %.2f, %.2f, %.2f | `%s` |" % ((label,) + tuple(rgb) + (hexcode,)))

    w("")
    w("## Mutually exclusive variants")
    w("")
    w("Only one of each set is drawn at a time. Deliver all of them, aligned to each other:")
    w("")
    w("- Eyes: `eyes_open`, `eyes_half`, `eyes_closed`")
    w("- Mouth: `mouth_neutral`, `mouth_open`, `mouth_smile`")
    w("")
    w("---")
    w("")
    w("## Character layers")
    w("")
    w("Canvas %d x %d at 1x. Drawn back to front by `z`." % vbd_layers.CHARACTER_CANVAS)
    w("")
    w(table(vbd_layers.CHARACTER))
    w("")
    w("## Dragon layers")
    w("")
    w("Canvas %d x %d at 1x. Body and tail segments are separate layers so the rig can run"
      % vbd_layers.DRAGON_CANVAS)
    w("them along a spline with per-segment lag. Draw each segment **centred on the canvas**,")
    w("facing right; the rig positions and rotates it.")
    w("")
    w(table(vbd_layers.DRAGON))
    w("")
    w("## Scene backdrops")
    w("")
    w("Canvas %d x %d at 1x. Three layers per scene at different parallax depths; higher"
      % vbd_layers.SCENE_CANVAS)
    w("parallax means the layer moves more as the pointer travels.")
    w("")

    for scene, layers in sorted(vbd_layers.SCENES.items()):
        w("### `%s`" % scene)
        w("")
        w("| Layer | z | Parallax | Depth |")
        w("|---|---|---|---|")

        for layer in sorted(layers, key=lambda item: item["z"]):
            parallax = layer.get("parallax", 0.0)
            depth = ("furthest, moves least" if parallax < 0.3
                     else ("nearest, moves most" if parallax > 0.6 else "mid"))
            w("| `%s` | %d | %.2f | %s |" % (layer["name"], layer["z"], parallax, depth))

        w("")

    w("---")
    w("")
    w("## Animation channels")
    w("")
    w("What each channel does to a layer that declares it. A layer may declare several and")
    w("their effects compose. Channels the code does not recognise are ignored, so new ones")
    w("can be added to the art before the rig understands them.")
    w("")
    w("| Channel | Effect |")
    w("|---|---|")

    for channel in sorted(used):
        w("| `%s` | %s |" % (channel, describe_channel(channel)))

    w("")
    w("---")
    w("")
    w("## Delivering the files")
    w("")
    w("1. Export each layer at @2x, full canvas, transparent background.")
    w("2. Replace the matching files under `assets/layers/@2x_*.png`.")
    w("3. Run `python tools/postprocess.py assets` to crop, derive the 1x set and rewrite")
    w("   the manifest.")
    w("4. Rebuild. No source changes are needed.")
    w("")
    w("To regenerate the placeholders instead, or after editing `vbd_layers.py`:")
    w("")
    w("```")
    w("python tools/build_assets.py            # needs Blender; not needed to build the plugin")
    w("python tools/make_assets_doc.py         # regenerate this document")
    w("python tools/preview_assets.py character preview.png")
    w("```")
    w("")

    path = os.path.join(ROOT, "ASSETS.md")

    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out))

    print("wrote %s (%d layers documented)" % (path, len(vbd_layers.all_layers())))


main()
